criação das paginas
ryanp2dev/loja-v5 pull request #3
Opened 2022-05-29 16:02 UTC by ryanp2dev

2022-05-31 22:57 UTC, yoannes requested changes

2022-05-31 22:57 UTC, yoannes commented on src/css/style.css
>  }
É importante ter a ultima linha no arquivo, pode trazer erros quando colocar o site no ar

https://stackoverflow.com/a/44704969/4066787

2022-05-31 22:57 UTC, yoannes commented on src/js/controllers.js
>  }
É importante ter a ultima linha no arquivo, pode trazer erros quando colocar o site no ar

https://stackoverflow.com/a/44704969/4066787

2022-06-02 22:56 UTC, ryanp2dev commented on src/css/style.css
>  }
alteração feita, desculpa pela demora professor

2022-06-02 22:57 UTC, ryanp2dev commented on src/js/controllers.js
>  }
alteração feita, desculpa pela demora professor

2022-06-09 14:44 UTC, yoannes commented on src/js/controllers.js
>  }
perfeito!!

2022-06-09 14:44 UTC, yoannes commented on src/css/style.css
>  }
perfeito

2022-06-09 14:44 UTC, merged